title: "#notGDC"
email: notgdc@notgdc.io
description: >-
  a game development non-conference, for everyone!
baseurl: ""
url: "https://notgdc.io"

# Site Settings
locale: "en"
repository: "benui-dev/notgdc-site"

# Open Graph/Twitter default site image
social:
  type: Organization
og_image: "/assets/site-logo.png"

# Reading Files
include:
  - .htaccess
  - .well-known/atproto-did
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - README.md
  - tmp
  - raw
  - "*.bat"
keep_files:
  - .git
  - .svn
encoding: "utf-8"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: ["apos","apos","quot","quot"]
  enable_coderay: false

footer:
  links:
    - label: "Bluesky"
      icon: "bluesky"
      url: "https://bsky.app/profile/notgdc.io/"
    - label: "Mastodon"
      icon: "mastodon"
      url: "https://mastodon.gamedev.place/@notGDC"
    - label: "Discord"
      icon: "discord"
      url: "https://discord.notgdc.io/"
    - label: "YouTube"
      icon: "youtube"
      url: "https://www.youtube.com/channel/UC3YNwRnEvNLdmpt-m6JaOOA"
    - label: "Twitch"
      icon: "twitch"
      url: "https://www.twitch.tv/notGDC"

navigation:
  - display: Home
    path: index.html
  - display: FAQ
    path: _pages/faq.md
  - display: All Years
    path: _pages/archive.md
  - display: 2025
    path: _pages/2025.md
  - display: 2024
    path: _pages/2024.md
  - display: 2023
    path: _pages/2023.md
  - display: 2022
    path: _pages/2022.md
  - display: 2020
    path: _pages/2020.md
  - display: 2019
    path: _pages/2019.md
  - display: 2018
    path: _pages/2018.md
  - display: 2017
    path: _pages/2017.md

# Collections
collections:
  tags:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      theme: 2025
      layout: default
  # global defaults
  - scope:
      path: ""
    values:
      theme: 2025
      hide_title: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
- jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
